DROP TABLE T24_PARAMETERS_SOURCE;
CREATE TABLE T24_PARAMETERS_SOURCE(
  TABLE_NAME NVARCHAR2(30),
  PARAMETER_NAME NVARCHAR2(255),
  COLUMN_NAME NVARCHAR2(30),
  M_VALUE NVARCHAR2(30),
  PARAMETER_VALUE NVARCHAR2(255)
);
CREATE OR REPLACE VIEW T24_PARAMETERS_SOURCE_PROFILE AS 
SELECT TABLE_NAME, COUNT(1) COUNT
FROM   T24_PARAMETERS_SOURCE
GROUP  BY TABLE_NAME;

DROP TABLE T24_PARAMETERS_DESTINATION;
CREATE TABLE T24_PARAMETERS_DESTINATION(
  TABLE_NAME NVARCHAR2(30),
  PARAMETER_NAME NVARCHAR2(255),
  COLUMN_NAME NVARCHAR2(30),
  M_VALUE NVARCHAR2(30),
  PARAMETER_VALUE NVARCHAR2(255)
);
CREATE OR REPLACE VIEW T24_PARAMETERS_DESTINATION_PROFILE AS 
SELECT TABLE_NAME, COUNT(1) COUNT
FROM   T24_PARAMETERS_DESTINATION
GROUP  BY TABLE_NAME;
